/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prolab_2.Pages;

import com.mycompany.prolab_2.Trip;
import com.mycompany.prolab_2.entity.Admin;
import com.mycompany.prolab_2.entity.Company;
import com.mycompany.prolab_2.repository.CompanyRepository;
import com.mycompany.prolab_2.repository.TripRepository;
import com.mycompany.prolab_2.vehicles.Airplane;
import com.mycompany.prolab_2.vehicles.Bus;
import com.mycompany.prolab_2.vehicles.Train;
import com.mycompany.prolab_2.vehicles.Vehicle;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author oztur
 */
public class CompanyPanel extends javax.swing.JFrame {

    /**
     * Creates new form CompanyPanel
     */
    public CompanyPanel() {
        
        initComponents();
    }
    static int i=0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jAracList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jSeferList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(650, 300));

        jAracList.setBackground(new java.awt.Color(204, 255, 204));
        jAracList.setModel(new javax.swing.AbstractListModel<Vehicle>() {

            List<Vehicle> strings = Login.tmp.getVehicles();
            public int getSize() { return strings.size(); }
            public Vehicle getElementAt(int i) { return strings.get(i); }
        });
        jScrollPane1.setViewportView(jAracList);

        jSeferList.setBackground(new java.awt.Color(204, 255, 204));
        jSeferList.setModel(new javax.swing.AbstractListModel<Trip>() {
            List<Trip> strings = Login.tmp.getTrips();
            public int getSize() { return strings.size(); }
            public Trip getElementAt(int i) { return strings.get(i); }
        });
        jScrollPane2.setViewportView(jSeferList);

        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Araçlar :");

        jLabel2.setForeground(new java.awt.Color(0, 204, 0));
        jLabel2.setText("Seferler :");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("SİL");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 0));
        jButton2.setText("EKLE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(0, 255, 0));
        jButton3.setText("SİL");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 255, 0));
        jButton4.setText("EKLE");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(new java.awt.Color(0, 153, 0));
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Kar Hesapla");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(0, 102, 0));
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Ana Sayfaya Dön");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("ID");

        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Adı");

        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Yakıt");

        jLabel6.setForeground(new java.awt.Color(0, 153, 0));
        jLabel6.setText("Kapasite");

        jLabel7.setForeground(new java.awt.Color(0, 153, 0));
        jLabel7.setText("Sefer no");

        jLabel8.setForeground(new java.awt.Color(0, 153, 0));
        jLabel8.setText("Sefer no");

        jLabel9.setForeground(new java.awt.Color(0, 153, 0));
        jLabel9.setText("Şehirler");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addGap(12, 12, 12)
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGap(48, 48, 48)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLabel9))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addContainerGap(54, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jButton5)
                            .addComponent(jButton6))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jButton6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(5, 5, 5)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton1)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(jButton5)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       if(this.jAracList.getSelectedValue()!=null){
        CompanyRepository.aracSil(Login.tmp.getId(),this.jAracList.getSelectedValue().getAracID()); 
      } 
       else{
         JOptionPane.showConfirmDialog(null, "Lütfen silmek istediğinizaracı seçiniz.", " ", JOptionPane.WARNING_MESSAGE);
     }
       
        this.setVisible(false);
        CompanyPanel next=new CompanyPanel();
          next.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     
       if(this.jSeferList.getSelectedValue()!=null){
        CompanyRepository.tripSil(Login.tmp.getId(), this.jSeferList.getSelectedValue().getSeferNo());
      } 
       else{
         JOptionPane.showConfirmDialog(null, "Lütfen silmek istediğiniz seferi seçiniz.", " ", JOptionPane.WARNING_MESSAGE);
     }
       

        this.setVisible(false);
        CompanyPanel next=new CompanyPanel();
          next.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.setVisible(false);
        ilk next =new ilk();
       next.setVisible(true);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        String  tt = JOptionPane.showInputDialog(null, "Eklemek istediğiniz aracın türü:", "tt", JOptionPane.QUESTION_MESSAGE);
        
        String  at = JOptionPane.showInputDialog(null, "Eklemek istediğiniz aracın adı:", "at", JOptionPane.QUESTION_MESSAGE);
        String  bt = JOptionPane.showInputDialog(null, "Eklemek istediğiniz aracın yakıt türü:", "bt", JOptionPane.QUESTION_MESSAGE);
        String  yt = JOptionPane.showInputDialog(null, "Eklemek istediğiniz aracın kilometredeki yakıt maliyeti:", "dt", JOptionPane.QUESTION_MESSAGE);
        int ty=Integer.parseInt(yt);
        String  ct = JOptionPane.showInputDialog(null, "Eklemek istediğiniz aracın koltuk sayısı:", "ct", JOptionPane.QUESTION_MESSAGE);
        int tc=Integer.parseInt(ct);
        String  dt = JOptionPane.showInputDialog(null, "Eklemek istediğiniz aracın sefer nosu:", "dt", JOptionPane.QUESTION_MESSAGE);
        int td=Integer.parseInt(dt);
       
        
        if(tt.equals("otobus")){
            Bus newBus=new Bus("otobus",at,bt,tc,TripRepository.getTripBySeferNo(td),ty);
            CompanyRepository.aracEkle(Login.tmp.getId(),newBus);
           
        }
        else if(tt.equals("tren")){
            Train newTrain=new Train("tren",at,bt,tc,TripRepository.getTripBySeferNo(td),ty);
            CompanyRepository.aracEkle(Login.tmp.getId(),newTrain);
            
        }
        else if(tt.equals("ucak")){
            Airplane newPlane=new Airplane("ucak",at,bt,tc,TripRepository.getTripBySeferNo(td),ty);           
            CompanyRepository.aracEkle(Login.tmp.getId(),newPlane);
        }
        Login.tmp = CompanyRepository.getCompanyById(Login.tmp.getId());
        
        this.setVisible(false);
        CompanyPanel next=new CompanyPanel();
        next.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
      String  drs = JOptionPane.showInputDialog(null, "Eklemek istediğiniz seferin numarası ?", "drs", JOptionPane.QUESTION_MESSAGE);
      int trs=Integer.parseInt(drs);
      
       CompanyRepository.tripEkle(Login.tmp.getId(), TripRepository.listele().get(trs-1));
        
        this.setVisible(false);
        CompanyPanel next=new CompanyPanel();
        next.setVisible(true);
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        Company cmp =CompanyRepository.getCompanyById(Login.tmp.getId());
        
        JOptionPane.showMessageDialog(null, "Toplam yolcu Ücretleri: "+cmp.topBiletHesapla()+"\nHizmet bedeli: -"+Admin.bedel+"\nToplam yakıt masrafları: -"+cmp.yakitMaliyetHEsapla()+"\nToplam personal ücreti: -"+cmp.topPersonelUct()+"\n\n Toplam kar: "+cmp.karHesapla());
        
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CompanyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CompanyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CompanyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CompanyPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CompanyPanel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JList<Vehicle> jAracList;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<Trip> jSeferList;
    // End of variables declaration//GEN-END:variables
}
