/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.prolab_2.Pages;

import com.mycompany.prolab_2.Reservation;
import com.mycompany.prolab_2.Transport;
import com.mycompany.prolab_2.vehicles.Vehicle;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author oztur
 */
public class SeferPanel extends javax.swing.JFrame {
    
    public static Vehicle secPanelArac;
    public static int yolcuSay;
    public static String mesafe="";
    public static String fyt="";
    /**
     * Creates new form SeferPanel
     * @param transportList
     */
    public SeferPanel() {
        initComponents();
    }
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jListKoltuk = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jYolcuSay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(650, 300));

        jListKoltuk.setBackground(new java.awt.Color(204, 255, 204));
        jListKoltuk.setModel(new javax.swing.AbstractListModel<Transport>() {
            List<Transport> strings = KullanıcıPanel.tmpTransport;
            public int getSize() { return strings.size(); }
            public Transport getElementAt(int i) { return strings.get(i); }
        });
        jScrollPane1.setViewportView(jListKoltuk);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("Bulunan Seferler :");

        jButton1.setBackground(new java.awt.Color(0, 255, 0));
        jButton1.setText("GÖSTER");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 102, 0));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("GERİ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 153, 0));
        jLabel2.setText("Firma");

        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("Araç adı");

        jLabel4.setForeground(new java.awt.Color(0, 153, 0));
        jLabel4.setText("Güzergah");

        jLabel5.setForeground(new java.awt.Color(0, 153, 0));
        jLabel5.setText("Yolcu sayısı :");

        jYolcuSay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jYolcuSayActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(jYolcuSay, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 428, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel1)
                                            .addGap(38, 38, 38))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(26, 26, 26)))
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jYolcuSay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(27, 27, 27))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        if(jYolcuSay!=null){
             if(this.jListKoltuk.getSelectedValue()!=null){
        
        secPanelArac =  this.jListKoltuk.getSelectedValue().getFoundVehicle();
        Reservation resK =new Reservation();
        resK.setArac(SeferPanel.secPanelArac);
        resK.setRota(KullanıcıPanel.route1);
        if(fyt.isEmpty()){
            fyt+= resK.fiyatBUl();  
        }
        if(mesafe.isEmpty()){
            mesafe+=resK.mesafeHesapla();
        }
        KoltukSecPanel next =new KoltukSecPanel();
        this.setVisible(false);
        next.setVisible(true);
      }
     else{
         JOptionPane.showConfirmDialog(null, "Lütfen silmek istediğiniz firmayı seçiniz.", " ", JOptionPane.WARNING_MESSAGE);
     }
            
        }else{
            JOptionPane.showConfirmDialog(null, "Lütfen yolcu sayısını giriniz.", " ", JOptionPane.WARNING_MESSAGE);
        }
      
        yolcuSay=Integer.parseInt(jYolcuSay.getText());
        
     
          
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        KullanıcıPanel next =new KullanıcıPanel();
        this.setVisible(false);
        next.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jYolcuSayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jYolcuSayActionPerformed
        
    }//GEN-LAST:event_jYolcuSayActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JList<Transport> jListKoltuk;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jYolcuSay;
    // End of variables declaration//GEN-END:variables
}
